### ISSUE TITLE
AppDaemon install issues. 

### ISSUE THREAD

**Issue by michaeldvinci** [ESPresense/ad-espresense-ips#1]
**Describe the bug**
Chatted with you previously. Manual install [for me] across all version results in the following error: 'NoneType has no mqtt.unsubscribe'

Also, can't add appdaemon github repo as HACS repo.

**Expected behavior**
appdaemon app runs.

**Logs**
 'NoneType has no mqtt.unsubscribe'

**Hardware Details**
only esp32 dev kit. do we need gps modules to work with the appdaemon? If so, would [these](https://www.ebay.com/itm/265185009800) work?

**Screenshots**
n/a

**Comment by DTTerastar** [comment]
https://github.com/ESPresense/ad-espresense-ips check out the readme.  I Have all the info you should need there now.

**Comment by michaeldvinci** [comment]
+1 working for me.

**Comment by DTTerastar** [comment]
Awesome.
