### ISSUE TITLE
Precision improvement - Wrong values polluting calculations

### ISSUE THREAD

**Issue by stan69b** [ESPresense/ad-espresense-ips#14]
Hey, I've been playing a lot lately and have been having precision issues. I have 10 esp32 for 90m2. some walls are thick concrete, some in construction bricks (thiner) and juste small separations as well.  
I found out that most of the time, the beacon closest to the device has the right measurement,  
but a beacon from a "far away" room and a thick wall in between will return a wrong value that is also very close (1m/1.5m).  
Given this, I supposed that the algorithm was miscalculating the position because 2 opposite (or more) beacons are giving small values which tends to put my devices in the center of my floorplan.

I had some ideas to approach this problem : 
-  have a threshold or a diameter value in the config, Take the esp with the smallest value, and only take into account esps that are in range using smallest value esp as center and diameter value as .... diameter. Thing is, if the smallest value is a false one.... not good
- If I have 3 esps or more per room, maybe restrict detection to the room only and discard values from other esps, so we can have a more accurate per room detection. (but that would not be practical to setup for most people i suppose .... )
- Have a system of weight on each esps, and try to find a way to reliably give importance to the closest/more precise esps. Using the weight value, we could multiply each coordinates by its weight, hopefully, the calculation is taking a barycenter and this would filter out extreme values that have been deemed not important.

I suppose other ways are possible, I'm planning on trying to code it and make a Pull Request but I would like a little help on understanding the current code and have other ideas if you have any so we can come up with a robust and reliable solution.

Hope I made sense in all this, It's all guess work above, I might be wrong on some things.

**Comment by DTTerastar** [comment]
We minimize the error to find the "likely" position, we could weight the error by the rank of distance to correct for that effect.

**Comment by DTTerastar** [comment]
The other factor is i use an absorption factor of 3.5 and I do think that is too high.  We should allow the ESPs to have a different value.

**Comment by DTTerastar** [comment]
It's numpy.  Numpy is all matrix stuff.  I don't understand it either.  I just found it while googling...

**Comment by DTTerastar** [comment]
I'm focused on the C++ atm so I'm quite sure you'll get this done sooner :)

**Comment by stan69b** [comment]
Yeah different absorption factor would be nice.  
Hahaha I'll try to play with it then and see what happens

**Comment by DTTerastar** [comment]
I added absorption, have you had a chance to play?

**Comment by stan69b** [comment]
Hey, I looking into it but got taken by something else lately. Thanks for the update, I will try it asap :)

**Comment by stan69b** [comment]
Hey, started playing with the absorbsion values a little. I did find something weird but It could be coming from the floorplan creator... I'm not sure yet.
I turned off all esp32 but 3 near the office. Checked the values returned by each. From what I calculate from those 3 mesures it seems pretty accurate and in the office but i see that the final device position is no where near that and shows in the livingroom. The mqtt message for that device also gives livingroom as the current room. Any ideas ? Could there be a miscalculation somewhere or in some special cases ? (Mqtt giving the wrong room as well makes me believe the floorplan is not the problem though I could be wrong. If you can have a try on your side and see if the floorplan gives you the same result maybe.)
Have a nice week end, if you are an F1 fan, enjoy qualifying today and the race tomorrow :)

**Comment by DTTerastar** [comment]
Yeah, I'm still struggling w/ getting anything even close to correct.  I need to make an offline test because using live data just drives you mad.

**Comment by DTTerastar** [comment]
I've tested this and it works, closing!
