### ISSUE TITLE
Queried IDs not mapped in IPS

### ISSUE THREAD

**Issue by jimmyeao** [ESPresense/ad-espresense-ips#20]
I have a lot of apple devices that are duplicated, so use the query filter in espresense to identify them.
This works fine in espresense but they never show up in IPS if I use the queried id (e.g. apple:ipad6-4)

**Comment by jimmyeao** [comment]
Closing, seems its just slow to populate..

**Comment by DTTerastar** [comment]
It doesn't populate until it sees 3 distances since you can't run trilateration until then.  It could maybe just send it w/ position unknown.
